theme = "bogster"

[editor]
true-color = true
line-number = "relative"
auto-completion = true
# rulers = [100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true

