[general]
live_config_reload = true
import = [
  "keybindings.toml",
  "colors.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.95
startup_mode = "Windowed"
dynamic_title = false
dimensions = { columns = 170, lines = 39 }
padding = { x = 10, y = 5 }

[scrolling]
# default
# history = 10000

[font]
# default
# size = 11.25
normal = { family = "monospace", style = "Regular" }

[terminal]
shell = { args = ["-l"], program = "/bin/fish" }

[bell]
animation = "EaseOutQuint"
color = "0x1BA6FA"
duration = 300

[selection]
# default
# save_to_clipboard = false

[cursor]
style = "Underline"
thickness = 0.15
unfocused_hollow = true

[mouse]
hide_when_typing = true

[keyboard]
# see keybindings.toml

[debug]
# log_level = "Warn"
# persistent_logging = true
# print_events = true
#ref_test = false
# render_timer = true


