[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

# [colors.bright]
# black = "#6D7070"
# blue = "#1BA6FA"
# cyan = "#73FBF1"
# green = "#B8E466"
# magenta = "#A578EA"
# red = "#FF4352"
# white = "#FEFEF8"
# yellow = "#FFD750"
#
# [colors.cursor]
# cursor = "#FF261E"
# text = "#FF261E"
#
# [colors.normal]
# black = "#0d0d0d"
# blue = "#1BA6FA"
# cyan = "#21DEEF"
# green = "#A0E521"
# magenta = "#8763B8"
# red = "#FF301B"
# white = "#EBEBEB"
# yellow = "#FFC620"
#
# [colors.primary]
# background = "#292C3E"
# foreground = "#EBEBEB"

# https://github.com/alacritty/alacritty-theme/blob/master/themes/alabaster_dark.toml

[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'
