abbr tcp 'tmux save-buffer - | pbcopy'
abbr e 'emacsclient -t'
abbr ec 'emacsclient -c'
abbr vim 'nvim'
abbr vi 'nvim'
abbr tree 'tree -I node_modules'
abbr lah 'ls -lah'
abbr glo 'git log --oneline'
abbr nl 'bat -n'